name: "community.zabbix.zabbix-agent"
on:
  push:
    paths:
      - 'roles/zabbix-agent/**'
      - '.github/workflows/zabbix-agent.yml'
  pull_request:
    paths:
      - 'roles/zabbix-agent/**'
      - '.github/workflows/zabbix-agent.yml'
jobs:
  zabbix-agent:
    runs-on: ubuntu-18.04
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - distro: centos:7
            command: /usr/sbin/init
          - distro: centos:8
            command: /usr/sbin/init
          # - fedora:29
          # - fedora:28
          - distro: ubuntu:16.04
            command: /sbin/init
          - distro: ubuntu:18.04
            command: /lib/systemd/systemd
          - distro: ubuntu:20.04
            command: /lib/systemd/systemd
          - distro: debian:9
            command: /lib/systemd/systemd
        collection_role:
          - zabbix-agent
        zabbix_version:
          # - 3.2
          # - 3.4
          # - 4.0
          # - 4.2
          - 4.4
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/zabbix

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          echo $PWD
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install molecule yamllint ansible-lint docker

      - name: Run role test
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_COMMAND=${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          ZABBIX_VERSION=${{ matrix.zabbix_version }}
          molecule --debug test -s ${{ matrix.collection_role }}
